// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/routingstrategy"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// RoutingStrategyCreate is the builder for creating a RoutingStrategy entity.
type RoutingStrategyCreate struct {
	config
	mutation *RoutingStrategyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoutingStrategyCreate) SetCreatedAt(v time.Time) *RoutingStrategyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableCreatedAt(v *time.Time) *RoutingStrategyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoutingStrategyCreate) SetUpdatedAt(v time.Time) *RoutingStrategyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableUpdatedAt(v *time.Time) *RoutingStrategyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RoutingStrategyCreate) SetDeletedAt(v time.Time) *RoutingStrategyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableDeletedAt(v *time.Time) *RoutingStrategyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RoutingStrategyCreate) SetName(v string) *RoutingStrategyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RoutingStrategyCreate) SetDescription(v string) *RoutingStrategyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableDescription(v *string) *RoutingStrategyCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RoutingStrategyCreate) SetEnabled(v bool) *RoutingStrategyCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableEnabled(v *bool) *RoutingStrategyCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RoutingStrategyCreate) SetPriority(v int) *RoutingStrategyCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillablePriority(v *int) *RoutingStrategyCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *RoutingStrategyCreate) SetPlatform(v string) *RoutingStrategyCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillablePlatform(v *string) *RoutingStrategyCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *RoutingStrategyCreate) SetGroupID(v int64) *RoutingStrategyCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableGroupID(v *int64) *RoutingStrategyCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetMatchMode sets the "match_mode" field.
func (_c *RoutingStrategyCreate) SetMatchMode(v string) *RoutingStrategyCreate {
	_c.mutation.SetMatchMode(v)
	return _c
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableMatchMode(v *string) *RoutingStrategyCreate {
	if v != nil {
		_c.SetMatchMode(*v)
	}
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *RoutingStrategyCreate) SetConditions(v []domain.RoutingCondition) *RoutingStrategyCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *RoutingStrategyCreate) SetAction(v string) *RoutingStrategyCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *RoutingStrategyCreate) SetNillableAction(v *string) *RoutingStrategyCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetAccountIds sets the "account_ids" field.
func (_c *RoutingStrategyCreate) SetAccountIds(v []int64) *RoutingStrategyCreate {
	_c.mutation.SetAccountIds(v)
	return _c
}

// SetAccountPriorities sets the "account_priorities" field.
func (_c *RoutingStrategyCreate) SetAccountPriorities(v []int) *RoutingStrategyCreate {
	_c.mutation.SetAccountPriorities(v)
	return _c
}

// Mutation returns the RoutingStrategyMutation object of the builder.
func (_c *RoutingStrategyCreate) Mutation() *RoutingStrategyMutation {
	return _c.mutation
}

// Save creates the RoutingStrategy in the database.
func (_c *RoutingStrategyCreate) Save(ctx context.Context) (*RoutingStrategy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoutingStrategyCreate) SaveX(ctx context.Context) *RoutingStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingStrategyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingStrategyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoutingStrategyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if routingstrategy.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized routingstrategy.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := routingstrategy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if routingstrategy.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized routingstrategy.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := routingstrategy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := routingstrategy.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := routingstrategy.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := routingstrategy.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := routingstrategy.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		v := routingstrategy.DefaultMatchMode
		_c.mutation.SetMatchMode(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := routingstrategy.DefaultAction
		_c.mutation.SetAction(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoutingStrategyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoutingStrategy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RoutingStrategy.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RoutingStrategy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := routingstrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "RoutingStrategy.description"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RoutingStrategy.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "RoutingStrategy.priority"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "RoutingStrategy.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := routingstrategy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		return &ValidationError{Name: "match_mode", err: errors.New(`ent: missing required field "RoutingStrategy.match_mode"`)}
	}
	if v, ok := _c.mutation.MatchMode(); ok {
		if err := routingstrategy.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.match_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "RoutingStrategy.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := routingstrategy.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.action": %w`, err)}
		}
	}
	return nil
}

func (_c *RoutingStrategyCreate) sqlSave(ctx context.Context) (*RoutingStrategy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoutingStrategyCreate) createSpec() (*RoutingStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &RoutingStrategy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(routingstrategy.Table, sqlgraph.NewFieldSpec(routingstrategy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(routingstrategy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(routingstrategy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(routingstrategy.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(routingstrategy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(routingstrategy.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(routingstrategy.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(routingstrategy.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(routingstrategy.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(routingstrategy.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.MatchMode(); ok {
		_spec.SetField(routingstrategy.FieldMatchMode, field.TypeString, value)
		_node.MatchMode = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(routingstrategy.FieldConditions, field.TypeJSON, value)
		_node.Conditions = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(routingstrategy.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.AccountIds(); ok {
		_spec.SetField(routingstrategy.FieldAccountIds, field.TypeJSON, value)
		_node.AccountIds = value
	}
	if value, ok := _c.mutation.AccountPriorities(); ok {
		_spec.SetField(routingstrategy.FieldAccountPriorities, field.TypeJSON, value)
		_node.AccountPriorities = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoutingStrategy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoutingStrategyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RoutingStrategyCreate) OnConflict(opts ...sql.ConflictOption) *RoutingStrategyUpsertOne {
	_c.conflict = opts
	return &RoutingStrategyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoutingStrategy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoutingStrategyCreate) OnConflictColumns(columns ...string) *RoutingStrategyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoutingStrategyUpsertOne{
		create: _c,
	}
}

type (
	// RoutingStrategyUpsertOne is the builder for "upsert"-ing
	//  one RoutingStrategy node.
	RoutingStrategyUpsertOne struct {
		create *RoutingStrategyCreate
	}

	// RoutingStrategyUpsert is the "OnConflict" setter.
	RoutingStrategyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RoutingStrategyUpsert) SetUpdatedAt(v time.Time) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateUpdatedAt() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RoutingStrategyUpsert) SetDeletedAt(v time.Time) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateDeletedAt() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RoutingStrategyUpsert) ClearDeletedAt() *RoutingStrategyUpsert {
	u.SetNull(routingstrategy.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *RoutingStrategyUpsert) SetName(v string) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateName() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *RoutingStrategyUpsert) SetDescription(v string) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateDescription() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldDescription)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *RoutingStrategyUpsert) SetEnabled(v bool) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateEnabled() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldEnabled)
	return u
}

// SetPriority sets the "priority" field.
func (u *RoutingStrategyUpsert) SetPriority(v int) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdatePriority() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *RoutingStrategyUpsert) AddPriority(v int) *RoutingStrategyUpsert {
	u.Add(routingstrategy.FieldPriority, v)
	return u
}

// SetPlatform sets the "platform" field.
func (u *RoutingStrategyUpsert) SetPlatform(v string) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdatePlatform() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldPlatform)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *RoutingStrategyUpsert) SetGroupID(v int64) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateGroupID() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *RoutingStrategyUpsert) AddGroupID(v int64) *RoutingStrategyUpsert {
	u.Add(routingstrategy.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RoutingStrategyUpsert) ClearGroupID() *RoutingStrategyUpsert {
	u.SetNull(routingstrategy.FieldGroupID)
	return u
}

// SetMatchMode sets the "match_mode" field.
func (u *RoutingStrategyUpsert) SetMatchMode(v string) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldMatchMode, v)
	return u
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateMatchMode() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldMatchMode)
	return u
}

// SetConditions sets the "conditions" field.
func (u *RoutingStrategyUpsert) SetConditions(v []domain.RoutingCondition) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldConditions, v)
	return u
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateConditions() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldConditions)
	return u
}

// ClearConditions clears the value of the "conditions" field.
func (u *RoutingStrategyUpsert) ClearConditions() *RoutingStrategyUpsert {
	u.SetNull(routingstrategy.FieldConditions)
	return u
}

// SetAction sets the "action" field.
func (u *RoutingStrategyUpsert) SetAction(v string) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateAction() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldAction)
	return u
}

// SetAccountIds sets the "account_ids" field.
func (u *RoutingStrategyUpsert) SetAccountIds(v []int64) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldAccountIds, v)
	return u
}

// UpdateAccountIds sets the "account_ids" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateAccountIds() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldAccountIds)
	return u
}

// ClearAccountIds clears the value of the "account_ids" field.
func (u *RoutingStrategyUpsert) ClearAccountIds() *RoutingStrategyUpsert {
	u.SetNull(routingstrategy.FieldAccountIds)
	return u
}

// SetAccountPriorities sets the "account_priorities" field.
func (u *RoutingStrategyUpsert) SetAccountPriorities(v []int) *RoutingStrategyUpsert {
	u.Set(routingstrategy.FieldAccountPriorities, v)
	return u
}

// UpdateAccountPriorities sets the "account_priorities" field to the value that was provided on create.
func (u *RoutingStrategyUpsert) UpdateAccountPriorities() *RoutingStrategyUpsert {
	u.SetExcluded(routingstrategy.FieldAccountPriorities)
	return u
}

// ClearAccountPriorities clears the value of the "account_priorities" field.
func (u *RoutingStrategyUpsert) ClearAccountPriorities() *RoutingStrategyUpsert {
	u.SetNull(routingstrategy.FieldAccountPriorities)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RoutingStrategy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RoutingStrategyUpsertOne) UpdateNewValues() *RoutingStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(routingstrategy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoutingStrategy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RoutingStrategyUpsertOne) Ignore() *RoutingStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoutingStrategyUpsertOne) DoNothing() *RoutingStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoutingStrategyCreate.OnConflict
// documentation for more info.
func (u *RoutingStrategyUpsertOne) Update(set func(*RoutingStrategyUpsert)) *RoutingStrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoutingStrategyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RoutingStrategyUpsertOne) SetUpdatedAt(v time.Time) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateUpdatedAt() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RoutingStrategyUpsertOne) SetDeletedAt(v time.Time) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateDeletedAt() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RoutingStrategyUpsertOne) ClearDeletedAt() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RoutingStrategyUpsertOne) SetName(v string) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateName() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *RoutingStrategyUpsertOne) SetDescription(v string) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateDescription() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RoutingStrategyUpsertOne) SetEnabled(v bool) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateEnabled() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *RoutingStrategyUpsertOne) SetPriority(v int) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RoutingStrategyUpsertOne) AddPriority(v int) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdatePriority() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdatePriority()
	})
}

// SetPlatform sets the "platform" field.
func (u *RoutingStrategyUpsertOne) SetPlatform(v string) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdatePlatform() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdatePlatform()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RoutingStrategyUpsertOne) SetGroupID(v int64) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RoutingStrategyUpsertOne) AddGroupID(v int64) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateGroupID() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RoutingStrategyUpsertOne) ClearGroupID() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearGroupID()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *RoutingStrategyUpsertOne) SetMatchMode(v string) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateMatchMode() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateMatchMode()
	})
}

// SetConditions sets the "conditions" field.
func (u *RoutingStrategyUpsertOne) SetConditions(v []domain.RoutingCondition) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetConditions(v)
	})
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateConditions() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateConditions()
	})
}

// ClearConditions clears the value of the "conditions" field.
func (u *RoutingStrategyUpsertOne) ClearConditions() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearConditions()
	})
}

// SetAction sets the "action" field.
func (u *RoutingStrategyUpsertOne) SetAction(v string) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateAction() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateAction()
	})
}

// SetAccountIds sets the "account_ids" field.
func (u *RoutingStrategyUpsertOne) SetAccountIds(v []int64) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetAccountIds(v)
	})
}

// UpdateAccountIds sets the "account_ids" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateAccountIds() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateAccountIds()
	})
}

// ClearAccountIds clears the value of the "account_ids" field.
func (u *RoutingStrategyUpsertOne) ClearAccountIds() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearAccountIds()
	})
}

// SetAccountPriorities sets the "account_priorities" field.
func (u *RoutingStrategyUpsertOne) SetAccountPriorities(v []int) *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetAccountPriorities(v)
	})
}

// UpdateAccountPriorities sets the "account_priorities" field to the value that was provided on create.
func (u *RoutingStrategyUpsertOne) UpdateAccountPriorities() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateAccountPriorities()
	})
}

// ClearAccountPriorities clears the value of the "account_priorities" field.
func (u *RoutingStrategyUpsertOne) ClearAccountPriorities() *RoutingStrategyUpsertOne {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearAccountPriorities()
	})
}

// Exec executes the query.
func (u *RoutingStrategyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoutingStrategyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoutingStrategyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RoutingStrategyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RoutingStrategyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RoutingStrategyCreateBulk is the builder for creating many RoutingStrategy entities in bulk.
type RoutingStrategyCreateBulk struct {
	config
	err      error
	builders []*RoutingStrategyCreate
	conflict []sql.ConflictOption
}

// Save creates the RoutingStrategy entities in the database.
func (_c *RoutingStrategyCreateBulk) Save(ctx context.Context) ([]*RoutingStrategy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoutingStrategy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoutingStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoutingStrategyCreateBulk) SaveX(ctx context.Context) []*RoutingStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoutingStrategy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoutingStrategyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RoutingStrategyCreateBulk) OnConflict(opts ...sql.ConflictOption) *RoutingStrategyUpsertBulk {
	_c.conflict = opts
	return &RoutingStrategyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoutingStrategy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoutingStrategyCreateBulk) OnConflictColumns(columns ...string) *RoutingStrategyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoutingStrategyUpsertBulk{
		create: _c,
	}
}

// RoutingStrategyUpsertBulk is the builder for "upsert"-ing
// a bulk of RoutingStrategy nodes.
type RoutingStrategyUpsertBulk struct {
	create *RoutingStrategyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RoutingStrategy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RoutingStrategyUpsertBulk) UpdateNewValues() *RoutingStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(routingstrategy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoutingStrategy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RoutingStrategyUpsertBulk) Ignore() *RoutingStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoutingStrategyUpsertBulk) DoNothing() *RoutingStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoutingStrategyCreateBulk.OnConflict
// documentation for more info.
func (u *RoutingStrategyUpsertBulk) Update(set func(*RoutingStrategyUpsert)) *RoutingStrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoutingStrategyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RoutingStrategyUpsertBulk) SetUpdatedAt(v time.Time) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateUpdatedAt() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RoutingStrategyUpsertBulk) SetDeletedAt(v time.Time) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateDeletedAt() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RoutingStrategyUpsertBulk) ClearDeletedAt() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RoutingStrategyUpsertBulk) SetName(v string) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateName() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *RoutingStrategyUpsertBulk) SetDescription(v string) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateDescription() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RoutingStrategyUpsertBulk) SetEnabled(v bool) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateEnabled() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *RoutingStrategyUpsertBulk) SetPriority(v int) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RoutingStrategyUpsertBulk) AddPriority(v int) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdatePriority() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdatePriority()
	})
}

// SetPlatform sets the "platform" field.
func (u *RoutingStrategyUpsertBulk) SetPlatform(v string) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdatePlatform() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdatePlatform()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RoutingStrategyUpsertBulk) SetGroupID(v int64) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RoutingStrategyUpsertBulk) AddGroupID(v int64) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateGroupID() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RoutingStrategyUpsertBulk) ClearGroupID() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearGroupID()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *RoutingStrategyUpsertBulk) SetMatchMode(v string) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateMatchMode() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateMatchMode()
	})
}

// SetConditions sets the "conditions" field.
func (u *RoutingStrategyUpsertBulk) SetConditions(v []domain.RoutingCondition) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetConditions(v)
	})
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateConditions() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateConditions()
	})
}

// ClearConditions clears the value of the "conditions" field.
func (u *RoutingStrategyUpsertBulk) ClearConditions() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearConditions()
	})
}

// SetAction sets the "action" field.
func (u *RoutingStrategyUpsertBulk) SetAction(v string) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateAction() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateAction()
	})
}

// SetAccountIds sets the "account_ids" field.
func (u *RoutingStrategyUpsertBulk) SetAccountIds(v []int64) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetAccountIds(v)
	})
}

// UpdateAccountIds sets the "account_ids" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateAccountIds() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateAccountIds()
	})
}

// ClearAccountIds clears the value of the "account_ids" field.
func (u *RoutingStrategyUpsertBulk) ClearAccountIds() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearAccountIds()
	})
}

// SetAccountPriorities sets the "account_priorities" field.
func (u *RoutingStrategyUpsertBulk) SetAccountPriorities(v []int) *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.SetAccountPriorities(v)
	})
}

// UpdateAccountPriorities sets the "account_priorities" field to the value that was provided on create.
func (u *RoutingStrategyUpsertBulk) UpdateAccountPriorities() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.UpdateAccountPriorities()
	})
}

// ClearAccountPriorities clears the value of the "account_priorities" field.
func (u *RoutingStrategyUpsertBulk) ClearAccountPriorities() *RoutingStrategyUpsertBulk {
	return u.Update(func(s *RoutingStrategyUpsert) {
		s.ClearAccountPriorities()
	})
}

// Exec executes the query.
func (u *RoutingStrategyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RoutingStrategyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoutingStrategyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoutingStrategyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
