// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/routingstrategy"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// RoutingStrategy is the model entity for the RoutingStrategy schema.
type RoutingStrategy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 评估优先级，数值越小越先评估（first-match-wins）
	Priority int `json:"priority,omitempty"`
	// 生效平台，空字符串表示任意平台
	Platform string `json:"platform,omitempty"`
	// 生效分组 ID，NULL 表示全局生效
	GroupID *int64 `json:"group_id,omitempty"`
	// 策略内多条件的组合方式：all | any
	MatchMode string `json:"match_mode,omitempty"`
	// 匹配条件列表：[{type,op,value}]
	Conditions []domain.RoutingCondition `json:"conditions,omitempty"`
	// 动作：restrict（硬路由）| prefer（软优先回退）
	Action string `json:"action,omitempty"`
	// 目标账号 ID 列表
	AccountIds []int64 `json:"account_ids,omitempty"`
	// 与 account_ids 对齐的账号优先级数组（数值越小越优先；相同数值为同一优先级，再按负载/LRU 选择）
	AccountPriorities []int `json:"account_priorities,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoutingStrategy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case routingstrategy.FieldConditions, routingstrategy.FieldAccountIds, routingstrategy.FieldAccountPriorities:
			values[i] = new([]byte)
		case routingstrategy.FieldEnabled:
			values[i] = new(sql.NullBool)
		case routingstrategy.FieldID, routingstrategy.FieldPriority, routingstrategy.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case routingstrategy.FieldName, routingstrategy.FieldDescription, routingstrategy.FieldPlatform, routingstrategy.FieldMatchMode, routingstrategy.FieldAction:
			values[i] = new(sql.NullString)
		case routingstrategy.FieldCreatedAt, routingstrategy.FieldUpdatedAt, routingstrategy.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoutingStrategy fields.
func (_m *RoutingStrategy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case routingstrategy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case routingstrategy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case routingstrategy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case routingstrategy.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case routingstrategy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case routingstrategy.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case routingstrategy.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case routingstrategy.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case routingstrategy.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case routingstrategy.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case routingstrategy.FieldMatchMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_mode", values[i])
			} else if value.Valid {
				_m.MatchMode = value.String
			}
		case routingstrategy.FieldConditions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field conditions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Conditions); err != nil {
					return fmt.Errorf("unmarshal field conditions: %w", err)
				}
			}
		case routingstrategy.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case routingstrategy.FieldAccountIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field account_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AccountIds); err != nil {
					return fmt.Errorf("unmarshal field account_ids: %w", err)
				}
			}
		case routingstrategy.FieldAccountPriorities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field account_priorities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AccountPriorities); err != nil {
					return fmt.Errorf("unmarshal field account_priorities: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoutingStrategy.
// This includes values selected through modifiers, order, etc.
func (_m *RoutingStrategy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RoutingStrategy.
// Note that you need to call RoutingStrategy.Unwrap() before calling this method if this RoutingStrategy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoutingStrategy) Update() *RoutingStrategyUpdateOne {
	return NewRoutingStrategyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoutingStrategy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoutingStrategy) Unwrap() *RoutingStrategy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoutingStrategy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoutingStrategy) String() string {
	var builder strings.Builder
	builder.WriteString("RoutingStrategy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("match_mode=")
	builder.WriteString(_m.MatchMode)
	builder.WriteString(", ")
	builder.WriteString("conditions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Conditions))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("account_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountIds))
	builder.WriteString(", ")
	builder.WriteString("account_priorities=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountPriorities))
	builder.WriteByte(')')
	return builder.String()
}

// RoutingStrategies is a parsable slice of RoutingStrategy.
type RoutingStrategies []*RoutingStrategy
