// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/routingstrategy"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// RoutingStrategyUpdate is the builder for updating RoutingStrategy entities.
type RoutingStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *RoutingStrategyMutation
}

// Where appends a list predicates to the RoutingStrategyUpdate builder.
func (_u *RoutingStrategyUpdate) Where(ps ...predicate.RoutingStrategy) *RoutingStrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoutingStrategyUpdate) SetUpdatedAt(v time.Time) *RoutingStrategyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RoutingStrategyUpdate) SetDeletedAt(v time.Time) *RoutingStrategyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableDeletedAt(v *time.Time) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RoutingStrategyUpdate) ClearDeletedAt() *RoutingStrategyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *RoutingStrategyUpdate) SetName(v string) *RoutingStrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableName(v *string) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RoutingStrategyUpdate) SetDescription(v string) *RoutingStrategyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableDescription(v *string) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RoutingStrategyUpdate) SetEnabled(v bool) *RoutingStrategyUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableEnabled(v *bool) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *RoutingStrategyUpdate) SetPriority(v int) *RoutingStrategyUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillablePriority(v *int) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *RoutingStrategyUpdate) AddPriority(v int) *RoutingStrategyUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RoutingStrategyUpdate) SetPlatform(v string) *RoutingStrategyUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillablePlatform(v *string) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RoutingStrategyUpdate) SetGroupID(v int64) *RoutingStrategyUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableGroupID(v *int64) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RoutingStrategyUpdate) AddGroupID(v int64) *RoutingStrategyUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RoutingStrategyUpdate) ClearGroupID() *RoutingStrategyUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetMatchMode sets the "match_mode" field.
func (_u *RoutingStrategyUpdate) SetMatchMode(v string) *RoutingStrategyUpdate {
	_u.mutation.SetMatchMode(v)
	return _u
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableMatchMode(v *string) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetMatchMode(*v)
	}
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *RoutingStrategyUpdate) SetConditions(v []domain.RoutingCondition) *RoutingStrategyUpdate {
	_u.mutation.SetConditions(v)
	return _u
}

// AppendConditions appends value to the "conditions" field.
func (_u *RoutingStrategyUpdate) AppendConditions(v []domain.RoutingCondition) *RoutingStrategyUpdate {
	_u.mutation.AppendConditions(v)
	return _u
}

// ClearConditions clears the value of the "conditions" field.
func (_u *RoutingStrategyUpdate) ClearConditions() *RoutingStrategyUpdate {
	_u.mutation.ClearConditions()
	return _u
}

// SetAction sets the "action" field.
func (_u *RoutingStrategyUpdate) SetAction(v string) *RoutingStrategyUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RoutingStrategyUpdate) SetNillableAction(v *string) *RoutingStrategyUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAccountIds sets the "account_ids" field.
func (_u *RoutingStrategyUpdate) SetAccountIds(v []int64) *RoutingStrategyUpdate {
	_u.mutation.SetAccountIds(v)
	return _u
}

// AppendAccountIds appends value to the "account_ids" field.
func (_u *RoutingStrategyUpdate) AppendAccountIds(v []int64) *RoutingStrategyUpdate {
	_u.mutation.AppendAccountIds(v)
	return _u
}

// ClearAccountIds clears the value of the "account_ids" field.
func (_u *RoutingStrategyUpdate) ClearAccountIds() *RoutingStrategyUpdate {
	_u.mutation.ClearAccountIds()
	return _u
}

// SetAccountPriorities sets the "account_priorities" field.
func (_u *RoutingStrategyUpdate) SetAccountPriorities(v []int) *RoutingStrategyUpdate {
	_u.mutation.SetAccountPriorities(v)
	return _u
}

// AppendAccountPriorities appends value to the "account_priorities" field.
func (_u *RoutingStrategyUpdate) AppendAccountPriorities(v []int) *RoutingStrategyUpdate {
	_u.mutation.AppendAccountPriorities(v)
	return _u
}

// ClearAccountPriorities clears the value of the "account_priorities" field.
func (_u *RoutingStrategyUpdate) ClearAccountPriorities() *RoutingStrategyUpdate {
	_u.mutation.ClearAccountPriorities()
	return _u
}

// Mutation returns the RoutingStrategyMutation object of the builder.
func (_u *RoutingStrategyUpdate) Mutation() *RoutingStrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoutingStrategyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoutingStrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingStrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoutingStrategyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if routingstrategy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized routingstrategy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := routingstrategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoutingStrategyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := routingstrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := routingstrategy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMode(); ok {
		if err := routingstrategy.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.match_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := routingstrategy.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.action": %w`, err)}
		}
	}
	return nil
}

func (_u *RoutingStrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(routingstrategy.Table, routingstrategy.Columns, sqlgraph.NewFieldSpec(routingstrategy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(routingstrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(routingstrategy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(routingstrategy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(routingstrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(routingstrategy.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(routingstrategy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(routingstrategy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(routingstrategy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(routingstrategy.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(routingstrategy.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(routingstrategy.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(routingstrategy.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.MatchMode(); ok {
		_spec.SetField(routingstrategy.FieldMatchMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(routingstrategy.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConditions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingstrategy.FieldConditions, value)
		})
	}
	if _u.mutation.ConditionsCleared() {
		_spec.ClearField(routingstrategy.FieldConditions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(routingstrategy.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountIds(); ok {
		_spec.SetField(routingstrategy.FieldAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingstrategy.FieldAccountIds, value)
		})
	}
	if _u.mutation.AccountIdsCleared() {
		_spec.ClearField(routingstrategy.FieldAccountIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.AccountPriorities(); ok {
		_spec.SetField(routingstrategy.FieldAccountPriorities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAccountPriorities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingstrategy.FieldAccountPriorities, value)
		})
	}
	if _u.mutation.AccountPrioritiesCleared() {
		_spec.ClearField(routingstrategy.FieldAccountPriorities, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingstrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoutingStrategyUpdateOne is the builder for updating a single RoutingStrategy entity.
type RoutingStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoutingStrategyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoutingStrategyUpdateOne) SetUpdatedAt(v time.Time) *RoutingStrategyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RoutingStrategyUpdateOne) SetDeletedAt(v time.Time) *RoutingStrategyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableDeletedAt(v *time.Time) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RoutingStrategyUpdateOne) ClearDeletedAt() *RoutingStrategyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *RoutingStrategyUpdateOne) SetName(v string) *RoutingStrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableName(v *string) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RoutingStrategyUpdateOne) SetDescription(v string) *RoutingStrategyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableDescription(v *string) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RoutingStrategyUpdateOne) SetEnabled(v bool) *RoutingStrategyUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableEnabled(v *bool) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *RoutingStrategyUpdateOne) SetPriority(v int) *RoutingStrategyUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillablePriority(v *int) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *RoutingStrategyUpdateOne) AddPriority(v int) *RoutingStrategyUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RoutingStrategyUpdateOne) SetPlatform(v string) *RoutingStrategyUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillablePlatform(v *string) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RoutingStrategyUpdateOne) SetGroupID(v int64) *RoutingStrategyUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableGroupID(v *int64) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RoutingStrategyUpdateOne) AddGroupID(v int64) *RoutingStrategyUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RoutingStrategyUpdateOne) ClearGroupID() *RoutingStrategyUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetMatchMode sets the "match_mode" field.
func (_u *RoutingStrategyUpdateOne) SetMatchMode(v string) *RoutingStrategyUpdateOne {
	_u.mutation.SetMatchMode(v)
	return _u
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableMatchMode(v *string) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetMatchMode(*v)
	}
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *RoutingStrategyUpdateOne) SetConditions(v []domain.RoutingCondition) *RoutingStrategyUpdateOne {
	_u.mutation.SetConditions(v)
	return _u
}

// AppendConditions appends value to the "conditions" field.
func (_u *RoutingStrategyUpdateOne) AppendConditions(v []domain.RoutingCondition) *RoutingStrategyUpdateOne {
	_u.mutation.AppendConditions(v)
	return _u
}

// ClearConditions clears the value of the "conditions" field.
func (_u *RoutingStrategyUpdateOne) ClearConditions() *RoutingStrategyUpdateOne {
	_u.mutation.ClearConditions()
	return _u
}

// SetAction sets the "action" field.
func (_u *RoutingStrategyUpdateOne) SetAction(v string) *RoutingStrategyUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RoutingStrategyUpdateOne) SetNillableAction(v *string) *RoutingStrategyUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAccountIds sets the "account_ids" field.
func (_u *RoutingStrategyUpdateOne) SetAccountIds(v []int64) *RoutingStrategyUpdateOne {
	_u.mutation.SetAccountIds(v)
	return _u
}

// AppendAccountIds appends value to the "account_ids" field.
func (_u *RoutingStrategyUpdateOne) AppendAccountIds(v []int64) *RoutingStrategyUpdateOne {
	_u.mutation.AppendAccountIds(v)
	return _u
}

// ClearAccountIds clears the value of the "account_ids" field.
func (_u *RoutingStrategyUpdateOne) ClearAccountIds() *RoutingStrategyUpdateOne {
	_u.mutation.ClearAccountIds()
	return _u
}

// SetAccountPriorities sets the "account_priorities" field.
func (_u *RoutingStrategyUpdateOne) SetAccountPriorities(v []int) *RoutingStrategyUpdateOne {
	_u.mutation.SetAccountPriorities(v)
	return _u
}

// AppendAccountPriorities appends value to the "account_priorities" field.
func (_u *RoutingStrategyUpdateOne) AppendAccountPriorities(v []int) *RoutingStrategyUpdateOne {
	_u.mutation.AppendAccountPriorities(v)
	return _u
}

// ClearAccountPriorities clears the value of the "account_priorities" field.
func (_u *RoutingStrategyUpdateOne) ClearAccountPriorities() *RoutingStrategyUpdateOne {
	_u.mutation.ClearAccountPriorities()
	return _u
}

// Mutation returns the RoutingStrategyMutation object of the builder.
func (_u *RoutingStrategyUpdateOne) Mutation() *RoutingStrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the RoutingStrategyUpdate builder.
func (_u *RoutingStrategyUpdateOne) Where(ps ...predicate.RoutingStrategy) *RoutingStrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoutingStrategyUpdateOne) Select(field string, fields ...string) *RoutingStrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoutingStrategy entity.
func (_u *RoutingStrategyUpdateOne) Save(ctx context.Context) (*RoutingStrategy, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingStrategyUpdateOne) SaveX(ctx context.Context) *RoutingStrategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoutingStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoutingStrategyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if routingstrategy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized routingstrategy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := routingstrategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoutingStrategyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := routingstrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := routingstrategy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMode(); ok {
		if err := routingstrategy.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.match_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := routingstrategy.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RoutingStrategy.action": %w`, err)}
		}
	}
	return nil
}

func (_u *RoutingStrategyUpdateOne) sqlSave(ctx context.Context) (_node *RoutingStrategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(routingstrategy.Table, routingstrategy.Columns, sqlgraph.NewFieldSpec(routingstrategy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoutingStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routingstrategy.FieldID)
		for _, f := range fields {
			if !routingstrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != routingstrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(routingstrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(routingstrategy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(routingstrategy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(routingstrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(routingstrategy.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(routingstrategy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(routingstrategy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(routingstrategy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(routingstrategy.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(routingstrategy.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(routingstrategy.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(routingstrategy.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.MatchMode(); ok {
		_spec.SetField(routingstrategy.FieldMatchMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(routingstrategy.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConditions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingstrategy.FieldConditions, value)
		})
	}
	if _u.mutation.ConditionsCleared() {
		_spec.ClearField(routingstrategy.FieldConditions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(routingstrategy.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountIds(); ok {
		_spec.SetField(routingstrategy.FieldAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingstrategy.FieldAccountIds, value)
		})
	}
	if _u.mutation.AccountIdsCleared() {
		_spec.ClearField(routingstrategy.FieldAccountIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.AccountPriorities(); ok {
		_spec.SetField(routingstrategy.FieldAccountPriorities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAccountPriorities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, routingstrategy.FieldAccountPriorities, value)
		})
	}
	if _u.mutation.AccountPrioritiesCleared() {
		_spec.ClearField(routingstrategy.FieldAccountPriorities, field.TypeJSON)
	}
	_node = &RoutingStrategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingstrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
